# Generated by Django 3.0.1 on 2022-05-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=40, null=True)),
                ('designation', models.CharField(max_length=30, null=True)),
                ('exp', models.IntegerField(null=True)),
                ('contactno', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
